services:
  phonebook:
    container_name: phonebook
    build:
      context: . #current directory
    ports:
      - "8080:8080"
    volumes:
      - ./logs:/logs
    depends_on:
      - mysql
    environment:
    #spring will automatically recognize the variables by the prefix
    #and reconcile it with the values stored in the .env file at the root and apply it to the mysql configuration info in applications.yml
    #this url uses the service name 'mysql' as defined in docker-compose
    #as the hostname
      SPRING_DATASOURCE_URL: jdbc:mysql://mysql:3306/${MYSQL_DATABASE}
      SPRING_DATASOURCE_USERNAME: ${DB_USERNAME}
      SPRING_DATASOURCE_PASSWORD: ${DB_PASSWORD}
      Initial_Admin_Username: ${Initial_Admin_Username}
      Initial_Admin_Password: ${Initial_Admin_Password}
    #health check to ensure requests aren't made until ready
    healthcheck:
    #endpoint is created by spring-boot-starter-actuator dependency
      #-f makes curl exit if exit code is >=400(request failed)
      test: ["CMD", "curl", "-f", "http://localhost:8080/actuator/health"]
      interval: 10s #repeat test every 10s
      timeout: 10s #docker will wait 10 seconds for curl command to complete
      retries: 10 #retry ten times, since container can take awhile to start up
  
  postman-tests:
    container_name: postman-tests
    build:
      context: ./postman-tests #look in this file for the docker containing postman tests
    #this docker container won't start until phonebook is up and running
    volumes:
      - ./logs:/logs
    depends_on: 
      phonebook:
        condition: service_healthy
    #tells docker to run the test container in the same network as the
    #PhoneBook. Basically lets both use localhost
    network_mode: "service:phonebook"
    #shut down application if tests fail
    command:
      - run
      - /etc/newman/PhoneBook_API_Test.postman_collection.json
      - --environment
      - /etc/newman/Testing_Environment.postman_environment.json
      - --reporters
      - cli,junit
      - --delay-request
      - "500"

  mysql:
    image: mysql:8.0
    container_name: phonebook_db
    restart: always
    environment:
    #mandatory env variables for the mysql image
      MYSQL_DATABASE: ${MYSQL_DATABASE}
      MYSQL_USER: ${DB_USERNAME}
      MYSQL_PASSWORD: ${DB_PASSWORD}
      MYSQL_ROOT_PASSWORD: ${MYSQL_ROOT_PASSWORD}
    volumes:
    #database data will be mounted to a file in this folder
      - db_data:/var/lib/mysql #mysql image uses this specific path as the default for storing data
    ports:
      - "3306:3306"
volumes:
#this volume is created and managed by docker
  db_data:
