
#MySQL Database Configuration
spring:
  application:
    name: PhoneBook
  datasource:
    url: jdbc:mysql://localhost:3306/PhoneBook
    username: ${DB_USERNAME}
    password: ${DB_PASSWORD}
    driver-class-name: com.mysql.cj.jdbc.Driver
  jpa:
    hibernate:
    #update schema after every change, won't drop table
      ddl-auto: update
      show-sql: true
      properties:
        hibernate.dialect: org.hibernate.dialect.MySQL8Dialect
        hibernate.format_sql: true